name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/checkout-action@v1

      - name: Exercise encrypt
        id: encrypt
        uses: ./
        with:
          data: foobar
          operation: encrypt

      - name: Exercise decrypt
        id: decrypt
        uses: ./
        with:
          data: ${{ steps.encrypt.outputs.result }}
          operation: decrypt

      - name: Verify
        env:
          ENCRYPTED: ${{ steps.encrypt.outputs.result }}
          DECRYPTED: ${{ steps.decrypt.outputs.result }}
        run: |
          set -x
          [[ "${#ENCRYPTED}" -ge 20 ]]
          test "${DECRYPTED}" = "foobar"
