name: Test
on:
  workflow_dispatch:
  pull_request:
    paths: ["action.yml", ".github/workflows/test.yml"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

defaults:
  run:
    shell: bash

jobs:
  test-encrypt:
    name: Test encrypt
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    outputs:
      result: ${{ steps.exercise.outputs.result }}
    steps:
      - name: Checkout
        uses: tmknom/secure-checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          data: Provide a sufficiently long text to avoid encountering a 'bad decrypt' error.
          operation: encrypt

      - name: Verify
        env:
          ENCRYPTED: ${{ steps.exercise.outputs.result }}
        run: |
          set -x
          [[ "${#ENCRYPTED}" -ge 100 ]]

  test-decrypt:
    name: Test decrypt
    needs: [test-encrypt]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: tmknom/secure-checkout-action@v1

      - name: Exercise
        id: exercise
        uses: ./
        with:
          data: ${{ needs.test-encrypt.outputs.result }}
          operation: decrypt

      - name: Verify
        env:
          DECRYPTED: ${{ steps.exercise.outputs.result }}
        run: |
          set -x
          test "${DECRYPTED}" = "Provide a sufficiently long text to avoid encountering a 'bad decrypt' error."
